### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by NexusTheBrony** [Hax4Ever/SuccubisWrath#1]
I understand this mod is mainly meant as a personal project, but could you do us a favor and _not_ modify vanilla textures in the main mod? I understand the need to modify vanilla content, but changing textures is unnecessary

**Comment by NexusTheBrony** [comment]
i'm not saying to stop modifying textures, but u can do that in a separate mod

**Comment by HermitBoy** [comment]
I like what you've done so far, personally. The texture and music changes took me by surprise last update, no idea where they were coming from.
I LOVE the inclusion of monster girl enemies like succubi, slime girls, centaurs, etc. ^_^ No one's made anything close to that kind of content before, so I greatly approve. This is why I watched/starred this mod, it's great. I would have commented on the tModloader forum, but the "visit homepage" button took me here, so that was all I had to give feedback with.
I like all the parts of this so far. ^_^

**Comment by NexusTheBrony** [comment]
@HermitBoy this is not the thread for feedback. this is my issue with the fact that the creator is modifying vanilla textures unnecessarily.

@Hax4Ever I really do like the textures, but I don't think they should b forced on any1 who wants to use this mod

**Comment by NexusTheBrony** [comment]
@Hax4Ever are you going to post?
